---
# tasks file forhaproxy
- name: Install the haproxy package
  package:
    name: haproxy
    state: latest

- name: configure haproxy
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy

- name: enable HAProxy
  service:
    name: haproxy
    state: started
    enabled: true

