---
- hosts: all
  become: yes
  roles:
    - common 
  tags:
    - common

- hosts: frontends, apps
  become: yes
  roles:
    - httpd
  tags:
    - httpd

- hosts: frontends
  become: yes
  roles:
    - haproxy
  tags:
    - haproxy
