---
- hosts: all
  become: yes
  roles:
    - common 
  tags:
    - common

- hosts: apps
  become: yes
  roles:
    - httpd
  tags:
    - httpd

- hosts: frontends
  become: yes
  roles:
    - haproxy
  tags:
    - haproxy

- hosts: apps
  become: yes
  roles:
    - tomcat
  tags:
    - tomcat
      
- hosts: appdbs
  become: yes
  roles:
    - postgres
  tags:
    - postgres
