---
# Create a security group
- name: Creamos el Security Group para las instancias
  os_security_group:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ security_group }}"
    description: Security group for {{ server_group }}

- name: Asignamos los permisos para el security group
  os_security_group_rule:
    cloud: "{{ cloud_name }}"
    security_group: "{{ rules.name }}"
    protocol: "{{ rules.protocol }}"
    port_range_min: "{{ rules.port | default('0') }}"
    port_range_max: "{{ rules.port | default('0') }}"
    remote_ip_prefix: "{{ rules.remote_ip | default('0.0.0.0/0') }}"
  loop: "{{ security_group_rules }}"
  loop_control:
    index_var: rules


