---
# tasks file for apache
- name: Install the apache package
  package:
    name: httpd
    state: latest

- name: enable apache at boot
  service:
    name: httpd
    state: started
    enabled: true
  when: '"app" in ansible_hostname'


