---
# tasks file for win_service_config
- name: Install multiple packages sequentially
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"
  win_chocolatey:
    name: "{{ package_name }}"
    state: present

- name: Set the log on user to Local Service
  win_service:
    name: "{{ service_name }}"
    state: started

- name: Firewall rule to allow {{ service_name }} on TCP port {{ local_port }}
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{ local_port }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

